import { getSession } from "@/lib/auth/storage";
import { getPortalSupabaseClient, getSupabaseStorageErrorMessage } from "@/lib/supabase/portal";
import { buildCorporateCardMemo } from "@/lib/corporate-card/memo";
import type { ScheduleAssignmentItem } from "@/lib/corporate-card/schedule";

interface ScheduleAssignmentRpcRow {
  schedule_date: string;
  schedule_item_id: string;
  photographer_profile_id: string | null;
  photographer_name: string;
  schedule_content: string;
}

interface PartnerEntryRow {
  id: string;
  schedule_date: string;
  schedule_item_id: string;
  photographer_profile_id: string | null;
  photographer_name: string;
  schedule_content: string;
  audio_man_name: string | null;
  senior_name: string | null;
  memo_text: string | null;
  partner_profile_id: string | null;
  created_at: string;
  updated_at: string;
}

const PARTNER_ENTRY_SELECT_BASE =
  "id, schedule_date, schedule_item_id, photographer_profile_id, photographer_name, schedule_content, audio_man_name, senior_name, partner_profile_id, created_at, updated_at";
const PARTNER_ENTRY_SELECT_WITH_MEMO =
  "id, schedule_date, schedule_item_id, photographer_profile_id, photographer_name, schedule_content, audio_man_name, senior_name, memo_text, partner_profile_id, created_at, updated_at";

export interface PartnerScheduleAssignment extends ScheduleAssignmentItem {
  audioManName: string;
  seniorName: string;
}

export interface MyScheduleAssignmentItem extends ScheduleAssignmentItem {
  audioManName: string;
  seniorName: string;
  autoGeneratedText: string;
  memoText: string;
  generatedText: string;
  isMemoCustom: boolean;
  missingFields: string[];
}

function rowToAssignment(row: ScheduleAssignmentRpcRow): ScheduleAssignmentItem {
  return {
    scheduleDate: row.schedule_date,
    scheduleItemId: row.schedule_item_id,
    photographerProfileId: row.photographer_profile_id,
    photographerName: row.photographer_name,
    scheduleContent: row.schedule_content,
  };
}

function dedupeAssignmentsByScheduleItemId<T extends ScheduleAssignmentItem>(assignments: T[]) {
  const seen = new Set<string>();
  return assignments.filter((assignment) => {
    if (seen.has(assignment.scheduleItemId)) return false;
    seen.add(assignment.scheduleItemId);
    return true;
  });
}

function getLogicalAssignmentKey(assignment: ScheduleAssignmentItem) {
  return [
    assignment.scheduleDate,
    assignment.photographerProfileId ?? assignment.photographerName,
    assignment.photographerName.trim(),
    assignment.scheduleContent.trim().replace(/\s+/g, " "),
  ].join("::");
}

function hasPartnerDetails(item: Pick<MyScheduleAssignmentItem, "audioManName" | "seniorName" | "memoText" | "autoGeneratedText" | "isMemoCustom">) {
  return Boolean(item.audioManName.trim() || item.seniorName.trim() || item.isMemoCustom || item.memoText.trim() !== item.autoGeneratedText.trim());
}

function dedupeMyAssignmentsByLogicalSchedule(items: MyScheduleAssignmentItem[]) {
  const map = new Map<string, MyScheduleAssignmentItem>();

  items.forEach((item) => {
    const key = getLogicalAssignmentKey(item);
    const existing = map.get(key);
    if (!existing) {
      map.set(key, item);
      return;
    }

    if (hasPartnerDetails(item) && !hasPartnerDetails(existing)) {
      map.set(key, item);
    }
  });

  return Array.from(map.values());
}

function getSchemaMessage(error: unknown, objectLabel: string) {
  return getSupabaseStorageErrorMessage(error, objectLabel);
}

function isMissingMemoTextColumnError(error: unknown) {
  const message = JSON.stringify(error ?? "").toLowerCase();
  return message.includes("memo_text") && message.includes("does not exist");
}

async function fetchPartnerEntryRowsByScheduleItemIds(
  supabase: Awaited<ReturnType<typeof getPortalSupabaseClient>>,
  ids: string[],
) {
  const { data, error } = await supabase
    .from("schedule_partner_entries")
    .select(PARTNER_ENTRY_SELECT_WITH_MEMO)
    .in("schedule_item_id", ids)
    .returns<PartnerEntryRow[]>();

  if (!error) {
    return (data ?? []) as PartnerEntryRow[];
  }

  if (!isMissingMemoTextColumnError(error)) {
    throw new Error(getSchemaMessage(error, "schedule_partner_entries"));
  }

  const fallback = await supabase
    .from("schedule_partner_entries")
    .select(PARTNER_ENTRY_SELECT_BASE)
    .in("schedule_item_id", ids)
    .returns<Omit<PartnerEntryRow, "memo_text">[]>();

  if (fallback.error) {
    throw new Error(getSchemaMessage(fallback.error, "schedule_partner_entries"));
  }

  return (fallback.data ?? []).map((row) => ({
    ...row,
    memo_text: null,
  })) as PartnerEntryRow[];
}

export async function fetchMyScheduleAssignments(monthKey: string) {
  const supabase = await getPortalSupabaseClient();
  const { data, error } = await supabase
    .rpc("get_my_schedule_assignment_items", { p_month_key: monthKey })
    .returns<ScheduleAssignmentRpcRow[]>();

  if (error) {
    throw new Error(getSchemaMessage(error, "내 일정"));
  }

  const rows = Array.isArray(data) ? (data as ScheduleAssignmentRpcRow[]) : [];
  return dedupeAssignmentsByScheduleItemId(rows.map(rowToAssignment));
}

export async function fetchPartnerScheduleAssignments(dateKey: string) {
  const supabase = await getPortalSupabaseClient();
  const { data, error } = await supabase
    .rpc("get_partner_schedule_assignment_items", { p_schedule_date: dateKey })
    .returns<ScheduleAssignmentRpcRow[]>();

  if (error) {
    throw new Error(getSchemaMessage(error, "파트너 일정"));
  }

  const rows = Array.isArray(data) ? (data as ScheduleAssignmentRpcRow[]) : [];
  const assignments = dedupeAssignmentsByScheduleItemId(rows.map(rowToAssignment));
  const ids = assignments.map((item) => item.scheduleItemId);
  if (ids.length === 0) {
    return [] as PartnerScheduleAssignment[];
  }

  const entryRows = await fetchPartnerEntryRowsByScheduleItemIds(supabase, ids);

  const entryMap = new Map((entryRows ?? []).map((row) => [row.schedule_item_id, row] as const));
  return assignments.map((assignment) => {
    const entry = entryMap.get(assignment.scheduleItemId);
    return {
      ...assignment,
      audioManName: entry?.audio_man_name ?? "",
      seniorName: entry?.senior_name ?? "",
    };
  });
}

export async function savePartnerScheduleEntry(input: PartnerScheduleAssignment) {
  const session = getSession();
  if (!session?.approved || session.role !== "partner") {
    throw new Error("파트너 권한이 필요합니다.");
  }

  const supabase = await getPortalSupabaseClient();
  const { error } = await supabase.from("schedule_partner_entries").upsert(
    {
      schedule_date: input.scheduleDate,
      schedule_item_id: input.scheduleItemId,
      photographer_profile_id: input.photographerProfileId,
      photographer_name: input.photographerName,
      schedule_content: input.scheduleContent,
      audio_man_name: input.audioManName.trim() || null,
      senior_name: input.seniorName.trim() || null,
      partner_profile_id: session.id,
    },
    { onConflict: "schedule_item_id" },
  );

  if (error) {
    throw new Error(getSchemaMessage(error, "schedule_partner_entries"));
  }
}

export async function saveMyScheduleAssignmentEntry(input: MyScheduleAssignmentItem) {
  const session = getSession();
  if (!session?.approved || session.role === "partner" || session.role === "observer") {
    throw new Error("내 일정 수정 권한이 필요합니다.");
  }

  const memoText = input.isMemoCustom && input.memoText.trim() !== input.autoGeneratedText.trim()
    ? input.memoText.trim()
    : null;
  const supabase = await getPortalSupabaseClient();
  const { error } = await supabase.rpc("upsert_my_schedule_partner_entry", {
    p_schedule_date: input.scheduleDate,
    p_schedule_item_id: input.scheduleItemId,
    p_audio_man_name: input.audioManName.trim() || null,
    p_senior_name: input.seniorName.trim() || null,
    p_memo_text: memoText,
  });

  if (error) {
    throw new Error(getSchemaMessage(error, "내 일정 수정"));
  }
}

export async function fetchMyScheduleAssignmentsWithPartnerInfo(monthKey: string) {
  const session = getSession();
  if (!session?.approved) {
    return [] as MyScheduleAssignmentItem[];
  }

  const supabase = await getPortalSupabaseClient();
  const assignments = await fetchMyScheduleAssignments(monthKey);
  const ids = assignments.map((item) => item.scheduleItemId);
  if (ids.length === 0) {
    return [] as MyScheduleAssignmentItem[];
  }

  const partnerRows = await fetchPartnerEntryRowsByScheduleItemIds(supabase, ids);

  const partnerMap = new Map((partnerRows ?? []).map((row) => [row.schedule_item_id, row] as const));

  const items = assignments.map((assignment) => {
    const partner = partnerMap.get(assignment.scheduleItemId);
    const audioManName = partner?.audio_man_name?.trim() ?? "";
    const seniorName = partner?.senior_name?.trim() ?? "";
    const autoGeneratedText = buildCorporateCardMemo({
      date: assignment.scheduleDate,
      scheduleContent: assignment.scheduleContent,
      userName: session.username,
      audioManName,
      seniorName,
    });
    const storedMemoText = partner?.memo_text?.trim() ?? "";
    const memoText = storedMemoText || autoGeneratedText;
    const missingFields = [
      audioManName ? "" : "오디오맨",
      seniorName ? "" : "수송부",
    ].filter(Boolean);

    return {
      ...assignment,
      audioManName,
      seniorName,
      autoGeneratedText,
      memoText,
      generatedText: memoText,
      isMemoCustom: Boolean(storedMemoText),
      missingFields,
    };
  });

  return dedupeMyAssignmentsByLogicalSchedule(items);
}
