-- Purpose:
--   Persist one 정제본 decision at a time without replacing the whole final_cut_v1 JSON object.
--   Keep an append-only history so a mistaken removal can be reconstructed later.

create table if not exists public.team_lead_final_cut_decision_history (
  id bigint generated by default as identity primary key,
  item_id text not null,
  legacy_item_id text,
  previous_decision text check (previous_decision is null or previous_decision in ('circle', 'triangle', 'cross')),
  decision text check (decision is null or decision in ('circle', 'triangle', 'cross')),
  changed_by uuid references public.profiles (id) on delete set null,
  changed_at timestamptz not null default timezone('utc', now())
);

create index if not exists team_lead_final_cut_decision_history_item_changed_idx
on public.team_lead_final_cut_decision_history (item_id, changed_at desc);

create index if not exists team_lead_final_cut_decision_history_changed_at_idx
on public.team_lead_final_cut_decision_history (changed_at desc);

alter table public.team_lead_final_cut_decision_history enable row level security;

drop policy if exists "team_lead_final_cut_decision_history_select_managers"
on public.team_lead_final_cut_decision_history;

create policy "team_lead_final_cut_decision_history_select_managers"
on public.team_lead_final_cut_decision_history
for select
to authenticated
using (
  public.current_profile_role() in ('team_lead', 'admin', 'desk')
  and public.current_profile_approved() = true
);

create or replace function public.update_team_lead_final_cut_decision(
  p_item_id text,
  p_decision text default null,
  p_legacy_item_id text default null
)
returns timestamptz
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_item_id text := trim(coalesce(p_item_id, ''));
  v_legacy_item_id text := nullif(trim(coalesce(p_legacy_item_id, '')), '');
  v_decision text := nullif(trim(coalesce(p_decision, '')), '');
  v_previous_decision text;
  v_state jsonb;
  v_updated_at timestamptz;
begin
  if v_user_id is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if public.current_profile_approved() is distinct from true
    or public.current_profile_role() not in ('team_lead', 'admin', 'desk') then
    raise exception '정제본 체크 저장 권한이 없습니다.';
  end if;

  if v_item_id = '' or length(v_item_id) > 2000 then
    raise exception '정제본 항목 키가 올바르지 않습니다.';
  end if;

  if v_decision is not null and v_decision not in ('circle', 'triangle', 'cross') then
    raise exception '정제본 체크 값이 올바르지 않습니다.';
  end if;

  insert into public.team_lead_state (key, state, updated_by)
  values ('final_cut_v1', '{}'::jsonb, v_user_id)
  on conflict (key) do nothing;

  select coalesce(state, '{}'::jsonb)
  into v_state
  from public.team_lead_state
  where key = 'final_cut_v1'
  for update;

  v_previous_decision := nullif(
    coalesce(v_state ->> v_item_id, case when v_legacy_item_id is not null then v_state ->> v_legacy_item_id end),
    ''
  );

  if v_legacy_item_id is not null and v_legacy_item_id <> v_item_id then
    v_state := v_state - v_legacy_item_id;
  end if;

  if v_decision is null then
    -- Keep an explicit empty tombstone on the stable key. Otherwise an older browser
    -- can re-upload the removed legacy key and make an unchecked item appear checked again.
    v_state := jsonb_set(v_state, array[v_item_id], to_jsonb(''::text), true);
  else
    v_state := jsonb_set(v_state, array[v_item_id], to_jsonb(v_decision), true);
  end if;

  update public.team_lead_state
  set
    state = v_state,
    updated_by = v_user_id
  where key = 'final_cut_v1'
  returning updated_at into v_updated_at;

  if v_previous_decision is distinct from v_decision then
    insert into public.team_lead_final_cut_decision_history (
      item_id,
      legacy_item_id,
      previous_decision,
      decision,
      changed_by
    )
    values (
      v_item_id,
      v_legacy_item_id,
      v_previous_decision,
      v_decision,
      v_user_id
    );
  end if;

  return v_updated_at;
end;
$$;

revoke execute on function public.update_team_lead_final_cut_decision(text, text, text)
from public, anon;

grant execute on function public.update_team_lead_final_cut_decision(text, text, text)
to authenticated;

revoke all on table public.team_lead_final_cut_decision_history from anon;
grant select on table public.team_lead_final_cut_decision_history to authenticated;
grant select, insert, update, delete on table public.team_lead_final_cut_decision_history to service_role;
grant usage, select on sequence public.team_lead_final_cut_decision_history_id_seq to service_role;
