"use client";

import { useEffect, useMemo, useState } from "react";
import {
  fetchMyScheduleAssignmentsWithPartnerInfo,
  saveMyScheduleFinalCutStatus,
  saveMyScheduleAssignmentEntry,
  type MyScheduleAssignmentItem,
} from "@/lib/corporate-card/storage";
import { buildCorporateCardMemo } from "@/lib/corporate-card/memo";
import { formatDateLabel, getCurrentMonthKey } from "@/lib/corporate-card/schedule";
import styles from "./CorporateCard.module.css";

const FINAL_CUT_STATUS_STORAGE_KEY = "corporate-card-final-cut-status-v1";

type MessageState = {
  tone: "note" | "warn";
  text: string;
};

function groupByDate(items: MyScheduleAssignmentItem[]) {
  return items.reduce((map, item) => {
    const existing = map.get(item.scheduleDate) ?? [];
    existing.push(item);
    map.set(item.scheduleDate, existing);
    return map;
  }, new Map<string, MyScheduleAssignmentItem[]>());
}

function readFinalCutStatus() {
  if (typeof window === "undefined") return {} as Record<string, boolean>;

  try {
    const parsed = JSON.parse(window.localStorage.getItem(FINAL_CUT_STATUS_STORAGE_KEY) ?? "{}");
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return {};

    return Object.fromEntries(
      Object.entries(parsed).filter(([, value]) => value === true),
    ) as Record<string, boolean>;
  } catch {
    return {};
  }
}

function writeFinalCutStatus(status: Record<string, boolean>) {
  try {
    window.localStorage.setItem(FINAL_CUT_STATUS_STORAGE_KEY, JSON.stringify(status));
  } catch {
    // Local status is convenience-only; storage failures should not block the page.
  }
}

function getFinalCutLogicalStatusKey(item: MyScheduleAssignmentItem) {
  return [
    item.scheduleDate,
    item.photographerProfileId ?? item.photographerName,
    item.photographerName.trim(),
    item.scheduleContent.trim().replace(/\s+/g, " "),
  ].join("::");
}

function getFinalCutStatusKeys(item: MyScheduleAssignmentItem) {
  return [item.scheduleItemId, getFinalCutLogicalStatusKey(item)];
}

function isFinalCutCompleted(item: MyScheduleAssignmentItem, status: Record<string, boolean>) {
  return item.finalCutCompleted || getFinalCutStatusKeys(item).some((key) => status[key]);
}

function getMissingFields(item: Pick<MyScheduleAssignmentItem, "audioManName" | "seniorName">) {
  return [
    item.audioManName.trim() ? "" : "오디오맨",
    item.seniorName.trim() ? "" : "수송부",
  ].filter(Boolean);
}

function getAutoGeneratedText(item: MyScheduleAssignmentItem) {
  return buildCorporateCardMemo({
    date: item.scheduleDate,
    scheduleContent: item.scheduleContent,
    userName: item.photographerName,
    audioManName: item.audioManName,
    seniorName: item.seniorName,
  });
}

function normalizeMyScheduleItem(item: MyScheduleAssignmentItem) {
  const autoGeneratedText = getAutoGeneratedText(item);
  const memoText = item.isMemoCustom ? item.memoText : autoGeneratedText;

  return {
    ...item,
    autoGeneratedText,
    memoText,
    generatedText: memoText,
    missingFields: getMissingFields(item),
  };
}

export function MyAssignmentsPage() {
  const [monthKey, setMonthKey] = useState(getCurrentMonthKey);
  const [items, setItems] = useState<MyScheduleAssignmentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [finalCutStatus, setFinalCutStatus] = useState<Record<string, boolean>>({});
  const [message, setMessage] = useState<MessageState | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draftItem, setDraftItem] = useState<MyScheduleAssignmentItem | null>(null);

  useEffect(() => {
    setFinalCutStatus(readFinalCutStatus());
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setMessage(null);
    setEditingId(null);
    setDraftItem(null);
    fetchMyScheduleAssignmentsWithPartnerInfo(monthKey)
      .then((nextItems) => {
        if (cancelled) return;
        setItems(nextItems);
        setFinalCutStatus((current) => {
          const localStatus = { ...readFinalCutStatus(), ...current };
          const nextStatus = { ...localStatus };
          nextItems.forEach((item) => {
            if (!item.finalCutCompleted && !getFinalCutStatusKeys(item).some((key) => localStatus[key])) return;
            getFinalCutStatusKeys(item).forEach((key) => {
              nextStatus[key] = true;
            });
          });
          writeFinalCutStatus(nextStatus);
          return nextStatus;
        });
      })
      .catch((error) => {
        if (cancelled) return;
        setMessage({ tone: "warn", text: error instanceof Error ? error.message : "내 일정을 불러오지 못했습니다." });
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [monthKey]);

  const grouped = useMemo(() => groupByDate(items), [items]);
  const [year, month] = monthKey.split("-");

  const copyMemo = async (item: MyScheduleAssignmentItem) => {
    await navigator.clipboard.writeText(item.generatedText);
    setCopiedId(item.scheduleItemId);
    window.setTimeout(() => setCopiedId(null), 1500);
  };

  const startEdit = (item: MyScheduleAssignmentItem) => {
    setEditingId(item.scheduleItemId);
    setDraftItem(item);
    setMessage(null);
  };

  const cancelEdit = () => {
    setEditingId(null);
    setDraftItem(null);
  };

  const updateDraft = (
    patch: Partial<MyScheduleAssignmentItem>,
    options: { memoEdited?: boolean; resetMemo?: boolean } = {},
  ) => {
    setDraftItem((current) => {
      if (!current) return current;
      const nextMemoCustom = options.resetMemo ? false : options.memoEdited ? true : current.isMemoCustom;
      return normalizeMyScheduleItem({
        ...current,
        ...patch,
        isMemoCustom: nextMemoCustom,
      });
    });
  };

  const saveDraft = async () => {
    if (!draftItem) return;
    const item = draftItem;
    setSavingId(item.scheduleItemId);
    setMessage(null);
    try {
      await saveMyScheduleAssignmentEntry(item);
      const savedItem = normalizeMyScheduleItem(item);
      setItems((currentItems) =>
        currentItems.map((currentItem) =>
          currentItem.scheduleItemId === savedItem.scheduleItemId ? savedItem : currentItem,
        ),
      );
      setEditingId(null);
      setDraftItem(null);
      setMessage({ tone: "note", text: "내 일정을 저장했습니다." });
    } catch (error) {
      setMessage({ tone: "warn", text: error instanceof Error ? error.message : "내 일정을 저장하지 못했습니다." });
    } finally {
      setSavingId((current) => (current === item.scheduleItemId ? null : current));
    }
  };

  const toggleFinalCutStatus = (item: MyScheduleAssignmentItem, checked: boolean) => {
    const previousStatus = finalCutStatus;
    setFinalCutStatus((current) => {
      const next = { ...current };
      if (checked) {
        getFinalCutStatusKeys(item).forEach((key) => {
          next[key] = true;
        });
      } else {
        getFinalCutStatusKeys(item).forEach((key) => {
          delete next[key];
        });
      }
      writeFinalCutStatus(next);
      return next;
    });
    setItems((currentItems) =>
      currentItems.map((currentItem) =>
        currentItem.scheduleItemId === item.scheduleItemId
          ? { ...currentItem, finalCutCompleted: checked }
          : currentItem,
      ),
    );
    void saveMyScheduleFinalCutStatus(item, checked).catch((error) => {
      writeFinalCutStatus(previousStatus);
      setFinalCutStatus(previousStatus);
      setItems((currentItems) =>
        currentItems.map((currentItem) =>
          currentItem.scheduleItemId === item.scheduleItemId
            ? { ...currentItem, finalCutCompleted: item.finalCutCompleted }
            : currentItem,
        ),
      );
      setMessage({
        tone: "warn",
        text: error instanceof Error ? error.message : "정제본 생성완료 상태를 저장하지 못했습니다.",
      });
    });
  };

  return (
    <section className={styles.page}>
      <article className="panel">
        <div className="panel-pad">
          <div className={styles.toolbar}>
            <div className={styles.header}>
              <span className="chip">내 일정</span>
              <h1 className={styles.title}>{year}년 {Number(month)}월 내 일정</h1>
            </div>
            <label className={styles.field}>
              <span>월 선택</span>
              <input className="field-input" type="month" value={monthKey} onChange={(event) => setMonthKey(event.target.value)} />
            </label>
          </div>
        </div>
      </article>

      <article className="panel">
        <div className="panel-pad">
          {message ? <div className={`status ${message.tone}`}>{message.text}</div> : null}
          {loading ? <div className="status note">내 일정을 불러오는 중입니다.</div> : null}
          {!loading && !items.length ? <div className="status note">이 달에 배정된 내 일정이 없습니다.</div> : null}
          <div className={styles.list}>
            {Array.from(grouped.entries()).map(([dateKey, dayItems]) => (
              <section key={dateKey} className={styles.dayBlock}>
                {dayItems.map((item) => {
                  const isEditing = editingId === item.scheduleItemId;
                  const displayItem = isEditing && draftItem?.scheduleItemId === item.scheduleItemId ? draftItem : item;
                  const isSaving = savingId === item.scheduleItemId;

                  return (
                    <article key={item.scheduleItemId} className={`${styles.itemCard} ${styles.myItemCard}`}>
                      <div className={styles.itemHead}>
                        <span className={styles.itemDate}>{formatDateLabel(dateKey)}</span>
                        <strong className={styles.itemTitle}>{item.scheduleContent}</strong>
                        <label className={styles.finalCutToggle}>
                          <span>{isFinalCutCompleted(item, finalCutStatus) ? "정제본 생성완료" : "정제본"}</span>
                          <input
                            type="checkbox"
                            checked={isFinalCutCompleted(item, finalCutStatus)}
                            onChange={(event) => toggleFinalCutStatus(item, event.target.checked)}
                          />
                        </label>
                      </div>

                      {isEditing ? (
                        <>
                          <div className={styles.myEditGrid}>
                            <label className={styles.field}>
                              <span>오디오맨</span>
                              <input
                                className="field-input"
                                value={displayItem.audioManName}
                                onChange={(event) => updateDraft({ audioManName: event.target.value })}
                              />
                            </label>
                            <label className={styles.field}>
                              <span>수송부</span>
                              <input
                                className="field-input"
                                value={displayItem.seniorName}
                                onChange={(event) => updateDraft({ seniorName: event.target.value })}
                              />
                            </label>
                          </div>
                          {displayItem.missingFields.length > 0 ? (
                            <span className={styles.pending}>누락: {displayItem.missingFields.join(", ")}</span>
                          ) : null}
                          <div className={styles.memoEditor}>
                            <textarea
                              className={`field-input ${styles.memoTextarea}`}
                              value={displayItem.memoText}
                              onChange={(event) => updateDraft({ memoText: event.target.value }, { memoEdited: true })}
                              rows={2}
                            />
                            <div className={styles.memoActions}>
                              {isSaving ? <span className={styles.autoSaveStatus}>저장 중</span> : null}
                              <button
                                type="button"
                                className="btn"
                                onClick={() => updateDraft({}, { resetMemo: true })}
                                disabled={!displayItem.isMemoCustom || isSaving}
                              >
                                자동문구
                              </button>
                              <button type="button" className="btn" onClick={cancelEdit} disabled={isSaving}>
                                취소
                              </button>
                              <button type="button" className="btn primary" onClick={saveDraft} disabled={isSaving}>
                                저장
                              </button>
                            </div>
                          </div>
                        </>
                      ) : (
                        <>
                          <div className={styles.metaGrid}>
                            <span className={styles.metaItem}>
                              오디오맨 <strong>{displayItem.audioManName || "입력 대기"}</strong>
                            </span>
                            <span className={styles.metaItem}>
                              수송부 <strong>{displayItem.seniorName || "입력 대기"}</strong>
                            </span>
                          </div>
                          {displayItem.missingFields.length > 0 ? (
                            <span className={styles.pending}>누락: {displayItem.missingFields.join(", ")}</span>
                          ) : null}
                          <div className={styles.memoBox}>
                            <p className={styles.memoText} title={displayItem.generatedText}>
                              {displayItem.generatedText}
                            </p>
                            <div className={styles.memoBoxActions}>
                              <button
                                type="button"
                                className="btn"
                                onClick={() => startEdit(item)}
                                disabled={Boolean(editingId) || isSaving}
                              >
                                수정
                              </button>
                              <button
                                type="button"
                                className={`btn primary ${styles.memoCopyButton}`}
                                onClick={() => copyMemo(displayItem)}
                                disabled={!displayItem.generatedText}
                              >
                                {copiedId === item.scheduleItemId ? "복사됨" : "복사"}
                              </button>
                            </div>
                          </div>
                        </>
                      )}
                    </article>
                  );
                })}
              </section>
            ))}
          </div>
        </div>
      </article>
    </section>
  );
}
