"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  fetchMyScheduleAssignmentsWithPartnerInfo,
  saveMyScheduleAssignmentEntry,
  type MyScheduleAssignmentItem,
} from "@/lib/corporate-card/storage";
import { buildCorporateCardMemo } from "@/lib/corporate-card/memo";
import { formatDateLabel, getCurrentMonthKey } from "@/lib/corporate-card/schedule";
import styles from "./CorporateCard.module.css";

const FINAL_CUT_STATUS_STORAGE_KEY = "corporate-card-final-cut-status-v1";
const AUTO_SAVE_DELAY_MS = 500;

type MessageState = {
  tone: "note" | "warn";
  text: string;
};

function groupByDate(items: MyScheduleAssignmentItem[]) {
  return items.reduce((map, item) => {
    const existing = map.get(item.scheduleDate) ?? [];
    existing.push(item);
    map.set(item.scheduleDate, existing);
    return map;
  }, new Map<string, MyScheduleAssignmentItem[]>());
}

function readFinalCutStatus() {
  if (typeof window === "undefined") return {} as Record<string, boolean>;

  try {
    const parsed = JSON.parse(window.localStorage.getItem(FINAL_CUT_STATUS_STORAGE_KEY) ?? "{}");
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return {};

    return Object.fromEntries(
      Object.entries(parsed).filter(([, value]) => value === true),
    ) as Record<string, boolean>;
  } catch {
    return {};
  }
}

function writeFinalCutStatus(status: Record<string, boolean>) {
  try {
    window.localStorage.setItem(FINAL_CUT_STATUS_STORAGE_KEY, JSON.stringify(status));
  } catch {
    // Local status is convenience-only; storage failures should not block the page.
  }
}

function getMissingFields(item: Pick<MyScheduleAssignmentItem, "audioManName" | "seniorName">) {
  return [
    item.audioManName.trim() ? "" : "오디오맨",
    item.seniorName.trim() ? "" : "수송부",
  ].filter(Boolean);
}

function getAutoGeneratedText(item: MyScheduleAssignmentItem) {
  return buildCorporateCardMemo({
    date: item.scheduleDate,
    scheduleContent: item.scheduleContent,
    userName: item.photographerName,
    audioManName: item.audioManName,
    seniorName: item.seniorName,
  });
}

function normalizeMyScheduleItem(item: MyScheduleAssignmentItem) {
  const autoGeneratedText = getAutoGeneratedText(item);
  const memoText = item.isMemoCustom ? item.memoText : autoGeneratedText;

  return {
    ...item,
    autoGeneratedText,
    memoText,
    generatedText: memoText,
    missingFields: getMissingFields(item),
  };
}

export function MyAssignmentsPage() {
  const [monthKey, setMonthKey] = useState(getCurrentMonthKey);
  const [items, setItems] = useState<MyScheduleAssignmentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [finalCutStatus, setFinalCutStatus] = useState<Record<string, boolean>>({});
  const [message, setMessage] = useState<MessageState | null>(null);
  const itemsRef = useRef<MyScheduleAssignmentItem[]>([]);
  const autoSaveTimersRef = useRef<Record<string, ReturnType<typeof setTimeout>>>({});

  useEffect(() => {
    setFinalCutStatus(readFinalCutStatus());
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setMessage(null);
    fetchMyScheduleAssignmentsWithPartnerInfo(monthKey)
      .then((nextItems) => {
        if (cancelled) return;
        itemsRef.current = nextItems;
        setItems(nextItems);
      })
      .catch((error) => {
        if (cancelled) return;
        setMessage({ tone: "warn", text: error instanceof Error ? error.message : "내 일정을 불러오지 못했습니다." });
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [monthKey]);

  useEffect(() => {
    return () => {
      Object.values(autoSaveTimersRef.current).forEach((timer) => clearTimeout(timer));
      autoSaveTimersRef.current = {};
    };
  }, []);

  const grouped = useMemo(() => groupByDate(items), [items]);
  const [year, month] = monthKey.split("-");

  const copyMemo = async (item: MyScheduleAssignmentItem) => {
    await navigator.clipboard.writeText(item.generatedText);
    setCopiedId(item.scheduleItemId);
    window.setTimeout(() => setCopiedId(null), 1500);
  };

  const persistItem = async (item: MyScheduleAssignmentItem) => {
    const existingTimer = autoSaveTimersRef.current[item.scheduleItemId];
    if (existingTimer) {
      clearTimeout(existingTimer);
      delete autoSaveTimersRef.current[item.scheduleItemId];
    }

    setSavingId(item.scheduleItemId);
    setMessage(null);
    try {
      await saveMyScheduleAssignmentEntry(item);
      setMessage({ tone: "note", text: "내 일정을 저장했습니다." });
    } catch (error) {
      setMessage({ tone: "warn", text: error instanceof Error ? error.message : "내 일정을 저장하지 못했습니다." });
    } finally {
      setSavingId((current) => (current === item.scheduleItemId ? null : current));
    }
  };

  const queueAutoSave = (item: MyScheduleAssignmentItem) => {
    const existingTimer = autoSaveTimersRef.current[item.scheduleItemId];
    if (existingTimer) {
      clearTimeout(existingTimer);
    }

    autoSaveTimersRef.current[item.scheduleItemId] = setTimeout(() => {
      void persistItem(item);
    }, AUTO_SAVE_DELAY_MS);
  };

  const updateItem = (
    scheduleItemId: string,
    patch: Partial<MyScheduleAssignmentItem>,
    options: { memoEdited?: boolean; resetMemo?: boolean } = {},
  ) => {
    const nextItems = itemsRef.current.map((item) => {
      if (item.scheduleItemId !== scheduleItemId) return item;
      const nextMemoCustom = options.resetMemo ? false : options.memoEdited ? true : item.isMemoCustom;
      return normalizeMyScheduleItem({
        ...item,
        ...patch,
        isMemoCustom: nextMemoCustom,
      });
    });
    const nextItem = nextItems.find((item) => item.scheduleItemId === scheduleItemId);

    itemsRef.current = nextItems;
    setItems(nextItems);

    if (nextItem) {
      queueAutoSave(nextItem);
    }
  };

  const saveImmediately = (scheduleItemId: string) => {
    const item = itemsRef.current.find((currentItem) => currentItem.scheduleItemId === scheduleItemId);
    if (!item) return;
    void persistItem(item);
  };

  const toggleFinalCutStatus = (item: MyScheduleAssignmentItem, checked: boolean) => {
    setFinalCutStatus((current) => {
      const next = { ...current };
      if (checked) {
        next[item.scheduleItemId] = true;
      } else {
        delete next[item.scheduleItemId];
      }
      writeFinalCutStatus(next);
      return next;
    });
  };

  return (
    <section className={styles.page}>
      <article className="panel">
        <div className="panel-pad">
          <div className={styles.toolbar}>
            <div className={styles.header}>
              <span className="chip">내 일정</span>
              <h1 className={styles.title}>{year}년 {Number(month)}월 내 일정</h1>
            </div>
            <label className={styles.field}>
              <span>월 선택</span>
              <input className="field-input" type="month" value={monthKey} onChange={(event) => setMonthKey(event.target.value)} />
            </label>
          </div>
        </div>
      </article>

      <article className="panel">
        <div className="panel-pad">
          {message ? <div className={`status ${message.tone}`}>{message.text}</div> : null}
          {loading ? <div className="status note">내 일정을 불러오는 중입니다.</div> : null}
          {!loading && !items.length ? <div className="status note">이 달에 배정된 내 일정이 없습니다.</div> : null}
          <div className={styles.list}>
            {Array.from(grouped.entries()).map(([dateKey, dayItems]) => (
              <section key={dateKey} className={styles.dayBlock}>
                {dayItems.map((item) => (
                  <article key={item.scheduleItemId} className={`${styles.itemCard} ${styles.myItemCard}`}>
                    <div className={styles.itemHead}>
                      <span className={styles.itemDate}>{formatDateLabel(dateKey)}</span>
                      <strong className={styles.itemTitle}>{item.scheduleContent}</strong>
                      <label className={styles.finalCutToggle}>
                        <span>{finalCutStatus[item.scheduleItemId] ? "정제본 생성완료" : "정제본"}</span>
                        <input
                          type="checkbox"
                          checked={Boolean(finalCutStatus[item.scheduleItemId])}
                          onChange={(event) => toggleFinalCutStatus(item, event.target.checked)}
                        />
                      </label>
                    </div>
                    <div className={styles.myEditGrid}>
                      <label className={styles.field}>
                        <span>오디오맨</span>
                        <input
                          className="field-input"
                          value={item.audioManName}
                          onChange={(event) => updateItem(item.scheduleItemId, { audioManName: event.target.value })}
                          onBlur={() => saveImmediately(item.scheduleItemId)}
                        />
                      </label>
                      <label className={styles.field}>
                        <span>수송부</span>
                        <input
                          className="field-input"
                          value={item.seniorName}
                          onChange={(event) => updateItem(item.scheduleItemId, { seniorName: event.target.value })}
                          onBlur={() => saveImmediately(item.scheduleItemId)}
                        />
                      </label>
                    </div>
                    {item.missingFields.length > 0 ? (
                      <span className={styles.pending}>누락: {item.missingFields.join(", ")}</span>
                    ) : null}
                    <div className={styles.memoEditor}>
                      <textarea
                        className={`field-input ${styles.memoTextarea}`}
                        value={item.memoText}
                        onChange={(event) => updateItem(item.scheduleItemId, { memoText: event.target.value }, { memoEdited: true })}
                        onBlur={() => saveImmediately(item.scheduleItemId)}
                        rows={2}
                      />
                      <div className={styles.memoActions}>
                        {savingId === item.scheduleItemId ? <span className={styles.autoSaveStatus}>자동 저장 중</span> : null}
                        <button
                          type="button"
                          className="btn"
                          onClick={() => updateItem(item.scheduleItemId, {}, { resetMemo: true })}
                          disabled={!item.isMemoCustom}
                        >
                          자동문구
                        </button>
                        <button
                          type="button"
                          className={`btn primary ${styles.memoCopyButton}`}
                          onClick={() => copyMemo(item)}
                          disabled={!item.generatedText}
                        >
                          {copiedId === item.scheduleItemId ? "복사됨" : "복사"}
                        </button>
                      </div>
                    </div>
                  </article>
                ))}
              </section>
            ))}
          </div>
        </div>
      </article>
    </section>
  );
}
