import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { GENERATED_NOTICE, markdownTable, repoRoot, writeGenerated } from "./utils.mjs";

const expectedDocs = [
  "docs/README.md",
  "docs/AGENT_MAP.md",
  "docs/ARCHITECTURE.md",
  "docs/FRONTEND.md",
  "docs/SUPABASE.md",
  "docs/SECURITY.md",
  "docs/RELIABILITY.md",
  "docs/QUALITY_SCORE.md",
  "docs/PRODUCT_CONTEXT.md",
  "docs/CHANGELOG_GUIDE.md",
  "docs/agent-harness/README.md",
  "docs/agent-harness/agent-routing.md",
  "docs/agent-harness/review-loop.md",
  "docs/agent-harness/prompt-template.md",
  "docs/agent-harness/verification-checklist.md",
  "docs/agent-harness/doc-gardening.md",
  "docs/agent-harness/human-escalation.md",
  "docs/architecture/overview.md",
  "docs/architecture/boundaries.md",
  "docs/architecture/nextjs-app-router.md",
  "docs/architecture/domain-layering.md",
  "docs/architecture/dependency-rules.md",
  "docs/product/overview.md",
  "docs/product/permissions.md",
  "docs/product/schedule.md",
  "docs/product/vacation.md",
  "docs/product/review-best-report.md",
  "docs/product/equipment.md",
  "docs/product/news-briefing.md",
  "docs/product/my-page.md",
  "docs/exec-plans/README.md",
  "docs/exec-plans/tech-debt-tracker.md",
];

const generatedDocs = [
  "docs/generated/route-map.md",
  "docs/generated/env-map.md",
  "docs/generated/supabase-map.md",
  "docs/generated/package-scripts.md",
  "docs/generated/dependency-map.md",
];

function exists(relative) {
  return fs.existsSync(path.join(repoRoot, relative));
}

function scoreRatio(done, total) {
  return total === 0 ? 0 : Math.round((done / total) * 100);
}

function runNode(script) {
  return spawnSync(process.execPath, [path.join(repoRoot, script)], {
    cwd: repoRoot,
    encoding: "utf8",
  });
}

function baseGeneratedFreshnessOk() {
  const baseDocs = [
    ["docs/generated/route-map.md", "scripts/harness/generate-route-map.mjs"],
    ["docs/generated/env-map.md", "scripts/harness/generate-env-map.mjs"],
    ["docs/generated/supabase-map.md", "scripts/harness/generate-supabase-map.mjs"],
    ["docs/generated/package-scripts.md", "scripts/harness/generate-package-scripts.mjs"],
  ];
  return baseDocs.every(([docRelative, scriptRelative]) => {
    const docPath = path.join(repoRoot, docRelative);
    const scriptPath = path.join(repoRoot, scriptRelative);
    if (!fs.existsSync(docPath) || !fs.existsSync(scriptPath)) return false;
    const text = fs.readFileSync(docPath, "utf8");
    return text.includes(`Generated by \`${scriptRelative}\``) && fs.statSync(docPath).mtimeMs + 1000 >= fs.statSync(scriptPath).mtimeMs;
  });
}

const docCoverage = scoreRatio(expectedDocs.filter(exists).length, expectedDocs.length);
const generatedCoverage = scoreRatio(generatedDocs.filter(exists).length, generatedDocs.length);
const freshnessOk = baseGeneratedFreshnessOk();
const boundary = runNode("scripts/harness/check-boundaries.mjs");

const routeMapText = exists("docs/generated/route-map.md")
  ? fs.readFileSync(path.join(repoRoot, "docs/generated/route-map.md"), "utf8")
  : "";
const envMapText = exists("docs/generated/env-map.md")
  ? fs.readFileSync(path.join(repoRoot, "docs/generated/env-map.md"), "utf8")
  : "";
const supabaseMapText = exists("docs/generated/supabase-map.md")
  ? fs.readFileSync(path.join(repoRoot, "docs/generated/supabase-map.md"), "utf8")
  : "";
const packageScriptText = exists("docs/generated/package-scripts.md")
  ? fs.readFileSync(path.join(repoRoot, "docs/generated/package-scripts.md"), "utf8")
  : "";

const metrics = [
  ["docs coverage", docCoverage, `${expectedDocs.filter(exists).length}/${expectedDocs.length} expected docs present`],
  ["generated docs coverage", generatedCoverage, `${generatedDocs.filter(exists).length}/${generatedDocs.length} generated docs present`],
  ["generated docs freshness", freshnessOk ? 100 : 40, freshnessOk ? "fresh" : "needs regeneration"],
  ["route map coverage", routeMapText.includes("app/(portal)") && routeMapText.includes("app/api") ? 100 : 50, "route-map generated from app/"],
  ["env map coverage", envMapText.includes("SUPABASE_SERVICE_ROLE_KEY") || envMapText.includes("NEXT_PUBLIC_SUPABASE_URL") ? 90 : 50, "env keys scanned without values"],
  ["Supabase/RLS visibility", supabaseMapText.includes("RLS Enabled Tables") && supabaseMapText.includes("Policies") ? 95 : 45, "SQL keywords summarized"],
  ["boundary check status", boundary.status === 0 ? 100 : 30, boundary.status === 0 ? "passed" : "failures present"],
  ["package script visibility", packageScriptText.includes("harness:all") ? 100 : 70, "package scripts mapped"],
];

const overall = Math.round(metrics.reduce((sum, [, value]) => sum + value, 0) / metrics.length);
const gaps = metrics.filter(([, value]) => value < 90).map(([name, value, note]) => `- ${name}: ${value}/100, ${note}`);

const scoreContent = [
  "## 자동 산출 점수",
  "",
  markdownTable(["항목", "점수", "근거"], metrics),
  "",
  `## 총점: ${overall}/100`,
  "",
  "## 부족한 부분",
  "",
  gaps.length ? gaps.join("\n") : "- 현재 자동 점검 기준에서 90점 미만 항목이 없습니다.",
  "",
  "## 주의",
  "",
  "- 이 점수는 하네스 가시성 점수이며 서비스 품질을 보증하지 않습니다.",
  "- lint/build/test 결과와 코드 리뷰를 별도로 확인해야 합니다.",
].join("\n");

writeGenerated("docs/generated/dependency-map.md", "quality-score.mjs", {
  title: "Dependency And Quality Map",
  content: [
    "## Harness Dependency Map",
    "",
    markdownTable(["입력", "출력/검사"], [
      ["app/**", "docs/generated/route-map.md"],
      [".env.example, process.env 사용처", "docs/generated/env-map.md"],
      ["supabase/*.sql", "docs/generated/supabase-map.md"],
      ["package.json scripts", "docs/generated/package-scripts.md"],
      ["AGENTS.md, docs/**/*.md", "scripts/harness/check-doc-links.mjs"],
      ["app/components/lib import/env 경계", "scripts/harness/check-boundaries.mjs"],
    ]),
    "",
    scoreContent,
  ].join("\n"),
});

const qualityPath = path.join(repoRoot, "docs/QUALITY_SCORE.md");
fs.writeFileSync(
  qualityPath,
  `# QUALITY_SCORE\n\n${GENERATED_NOTICE("quality-score.mjs")}\n${scoreContent}\n`,
  "utf8",
);

const trackerPath = path.join(repoRoot, "docs/exec-plans/tech-debt-tracker.md");
if (exists("docs/exec-plans/tech-debt-tracker.md")) {
  const current = fs.readFileSync(trackerPath, "utf8");
  const start = "<!-- harness-quality:start -->";
  const end = "<!-- harness-quality:end -->";
  const managed = [
    start,
    "## 자동 점검 메모",
    "",
    gaps.length ? gaps.join("\n") : "- 현재 자동 점검 기준에서 즉시 기록할 하네스 부채가 없습니다.",
    "",
    end,
  ].join("\n");
  const next = current.includes(start)
    ? current.replace(new RegExp(`${start}[\\s\\S]*?${end}`), managed)
    : `${current.trim()}\n\n${managed}\n`;
  fs.writeFileSync(trackerPath, next, "utf8");
}

console.log(`quality-score: ${overall}/100`);
if (boundary.status !== 0) process.exit(1);
