import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

export const GENERATED_NOTICE = (scriptName) =>
  `> Generated by \`scripts/harness/${scriptName}\` at ${new Date().toISOString()}.\n> Do not edit directly. Regenerate with the matching harness script.\n`;

const IGNORED_DIRS = new Set([
  ".git",
  ".next",
  ".next-dev",
  ".vercel",
  "node_modules",
  "playwright-report",
  "test-results",
  "coverage",
  "dist",
]);

export function toPosix(relativePath) {
  return relativePath.split(path.sep).join("/");
}

export function rel(filePath) {
  return toPosix(path.relative(repoRoot, filePath));
}

export function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

export function writeGenerated(relativePath, scriptName, body) {
  const target = path.join(repoRoot, relativePath);
  ensureDir(target);
  fs.writeFileSync(target, `# ${body.title}\n\n${GENERATED_NOTICE(scriptName)}\n${body.content.trim()}\n`, "utf8");
}

export function readTextIfExists(relativePath) {
  const target = path.join(repoRoot, relativePath);
  return fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
}

export function listFiles(startRelative, options = {}) {
  const start = path.join(repoRoot, startRelative);
  if (!fs.existsSync(start)) return [];
  const files = [];
  const extensions = options.extensions ? new Set(options.extensions) : null;

  function walk(current) {
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (!IGNORED_DIRS.has(entry.name)) walk(path.join(current, entry.name));
        continue;
      }
      if (!entry.isFile()) continue;
      const fullPath = path.join(current, entry.name);
      if (!extensions || extensions.has(path.extname(entry.name))) files.push(fullPath);
    }
  }

  walk(start);
  return files.sort((a, b) => rel(a).localeCompare(rel(b)));
}

export function listRepoFiles(options = {}) {
  return listFiles(".", options);
}

export function lineNumberForIndex(text, index) {
  return text.slice(0, index).split(/\r?\n/).length;
}

export function markdownTable(headers, rows) {
  const escapeCell = (value) => String(value ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>");
  return [
    `| ${headers.map(escapeCell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`),
  ].join("\n");
}

export function isClientComponentSource(source) {
  const stripped = source.replace(/^\uFEFF/, "").trimStart();
  return stripped.startsWith("\"use client\"") || stripped.startsWith("'use client'");
}

export function codeFiles() {
  return listRepoFiles({ extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"] }).filter((file) => {
    const relative = rel(file);
    return !relative.startsWith("scripts/harness/");
  });
}
